### ISSUE TITLE
Error "Cannot parse "//css_import..."" when referencing an assembly

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#189]
When having this line somewhere at the top of my script file:

```cs
//css_ref C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Build.dll
```

I get an error message:

> Cannot parse "//css_import..."

Full stack trace:

```txt
System.ApplicationException: Cannot parse "//css_import..."
   at csscript.CSharpParser.ImportInfo.InternalInit(String[] statementParts, Int32 startIndex)
   at csscript.CSharpParser.ImportInfo.ResolveStatement(String statement, String parentScript, String[] probinghDirs)
   at csscript.CSharpParser.Init(String code, String file, String[] directivesToSearch, String[] probingDirs)
   at csscript.CSharpParser.Construct(String script, Boolean isFile, String[] directivesToSearch, String[] probingDirs)
   at csscript.CSExecutor.Execute(String[] args, PrintDelegate printDelg, String primaryScript)
```

I've tried to escale the "(" and ")" like this:

```cs
//css_ref C:\Program Files ((x86))\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Build.dll
```

And also tried to enclose the path within single quotes or double quotes.

Still, I'm unable to get rid of the above error.

### My question

How can I `css_ref` an assembly that is located inside a path with both spaces and round brackets?

**Comment by oleg-shilo** [comment]
Hi Uwe. 
I cannot reproduce it. Seems to work for me:

![image](https://user-images.githubusercontent.com/16729806/75452910-2c9be680-59c7-11ea-8dea-1df991e3224d.png)

in v3.28.9
![image](https://user-images.githubusercontent.com/16729806/75452974-450c0100-59c7-11ea-86fe-8fe2d933d653.png)

Try to use envars: 
`//css_ref %PROGRAMFILES(X86)%\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Build.dll`

**Comment by cuiliang** [comment]
Version 3.30.0, also has this problem.
will NOT work :
```
//css_reference C:\Program Files (x86)\e-iceblue\Spire.Presentation\Bin\NET4.6\Spire.Presentation.dll;
```

will work:
```
//css_reference C:\Progra~1\e-iceblue\Spire.Presentation\Bin\NET4.6\Spire.Presentation.dll;
```

**Comment by oleg-shilo** [comment]
My apologies. i have retested again and found that Uwe's sample produces the error in 3.30.0 and v3.29.0 exactly as he indicated. Somehow I missed this point and got stuck on the "success" of V3.28.9.

I found the problem (in fact two) with the processing `//css_ref` and `//css_imp` having brackets in the path. 

Working on it...

**Comment by UweKeim** [comment]
From a quick look, it seems that your [`DirectiveDelimiters`](https://github.com/oleg-shilo/cs-script/blob/731e93c48eaec944163ddf51e63c470c7b78f91a/Source/.NET%20Core/CSScriptLib/src/CSScriptLib/csparser.cs#L1143) is the cause:

```csharp
public static char[] DirectiveDelimiters = new char[] { ';', '(', ')', '{', '}', ',' };
```

[In this line](https://github.com/oleg-shilo/cs-script/blob/731e93c48eaec944163ddf51e63c470c7b78f91a/Source/.NET%20Core/CSScriptLib/src/CSScriptLib/csparser.cs#L211) you are splitting by these delimiters.

Since  "C:\Program Files (x86)\..." contains `(` from the delimiters list, I do think this breaks the path resolver.

**Comment by oleg-shilo** [comment]
Yes it is the case. 
But the real problem is that the escaping technique (double bracket) does interfere with the splitByDelimiters. 
I plan to release the fix in a day or two

**Comment by oleg-shilo** [comment]
Guys, please test the v3.30.2 release:
https://github.com/oleg-shilo/cs-script/releases/tag/v3.30.2.0
```
Install-Package CS-Script -Version 3.30.2-HotFix
```
It should fix the problem.

**Comment by trivalik** [comment]
I have a similar issue with css_reference and tested it with Release v1.30.2.1-HotFix (probably a typo after v).
>System.ApplicationException: Cannot parse "//css_reference
   bei csscript.CSharpParser.ImportInfo.InternalInit(String[] statementParts, Int32 startIndex, String context)
   bei csscript.CSharpParser.ImportInfo.ResolveStatement(String statement, String parentScript, String[] probinghDirs, String context)
   bei csscript.CSharpParser.Init(String code, String file, String[] directivesToSearch, String[] probingDirs)
   bei csscript.CSharpParser.Construct(String script, Boolean isFile, String[] directivesToSearch, String[] probingDirs)
   bei csscript.CSExecutor.Execute(String[] args, PrintDelegate printDelg, String primaryScript)`

**Comment by oleg-shilo** [comment]
Please test it with https://www.nuget.org/packages/CS-Script/3.30.2-HotFix
thi should fix the problem. As soon as you guys confirm it does I will re-publish it as a proper release. Not a hot fix.

**Comment by cuiliang** [comment]
@oleg-shilo Seems not fixed.

```
//css_reference  C:\Program Files (x86)\aText\PInvoke.Kernel32.dll
```

093538,683异常：Cannot parse "//css_reference
在 csscript.CSharpParser.ImportInfo.InternalInit(String[] statementParts, Int32 startIndex, String context)
在 csscript.CSharpParser.ImportInfo.ResolveStatement(String statement, String parentScript, String[] probinghDirs, String context)
在 csscript.CSharpParser.Init(String code, String file, String[] directivesToSearch, String[] probingDirs)
在 csscript.CSharpParser..ctor(String code)
在 CSScriptLibrary.CodeDomEvaluator.GetReferencedAssemblies(String code, String[] searchDirs)
在 CSScriptLibrary.CodeDomEvaluator.ReferenceAssembliesFromCode(String code, String[] searchDirs)

**Comment by oleg-shilo** [comment]
Can you please send me the test project that exhibits this problem.
It will help greatly

**Comment by cuiliang** [comment]
Add the following code in test project will show the problem.
```
public class FileReference
    {
        [Fact]
        public void Test()
        {
            string code = @"//css_reference  C:\Program Files (x86)\TestProj\PInvoke.Kernel32.dll
using System.Windows.Forms;
public static void Exec(){            
            MessageBox.Show(""Hello World!"");
        }

";
            CSScript.EvaluatorConfig.Engine = EvaluatorEngine.CodeDom;
            IEvaluator evaluator = CSScript.Evaluator;


            //evaluator.Reset(false); //clear all ref assemblies
            evaluator
                .ReferenceAssembly(Assembly.GetExecutingAssembly())
                .ReferenceAssemblyOf<string>()
                .ReferenceAssemblyByName("System.Runtime") // System.Runtime.dll
                .ReferenceAssembliesFromCode(code);


            var assembly = evaluator.CompileMethod(code);

            var Exec = assembly.GetStaticMethod("*.Exec");
            Exec();


            assembly.UnloadOwnerDomain();

        }
    }
```

![image](https://user-images.githubusercontent.com/1972649/80852556-27c01100-8c5c-11ea-9658-74af536a5a59.png)

**Comment by oleg-shilo** [comment]
thank you

**Comment by oleg-shilo** [comment]
OK, tested. 

You code fails because you need to escape brackets:
```C#
//css_reference  C:\Program Files ((x86))\TestProj\PInvoke.Kernel32.dll
``` 
The escaping was broken and the latest patch addresses this very problem.
See https://www.cs-script.net/cs-script/help-legacy/Directives.html

Let me know if it helped.

As an improvement I have added the section about escaping in the CLI help (will be available in the next release):

![image](https://user-images.githubusercontent.com/16729806/80869343-45848900-8ce3-11ea-8d6b-e2ed1246c364.png)

**Comment by cuiliang** [comment]
Got it, Thank you!
