### ISSUE TITLE
Implementing a partial class with a circular css_import results in a recursion in CS-Script and results in a PathTooLongException

### ISSUE THREAD

**Issue by maettu-this** [oleg-shilo/cs-script#211]
This is a really painful one for me. After having upgraded from 3.28.3 to 3.30.3, the majority of our several 100 test scripts have broken. For a recursion somewhere in the depths of `fileparser.cs`.

First a minor one at help.txt line 274:
`cscs -config:set: ResolveRelativeFromParentScriptLocation = true`
...should be...
`cscs -config:set:ResolveRelativeFromParentScriptLocation=true`

Then the major issue, with files to reproduce it:
[Issue #211.zip](https://github.com/oleg-shilo/cs-script/files/5439327/Issue.211.zip)

To reproduce in PowerShell:
1. `\TestLibrary\TestA> .\cscs.exe -config:set:ResolveRelativeFromParentScriptLocation=true .\Main.cs`
2. `\TestLibrary\TestA> .\cscs.exe .\Main.cs`

Resulting in "Error: Specified file could not be compiled.":
[Result.txt](https://github.com/oleg-shilo/cs-script/files/5439338/Result.txt)

Screenshots:
1.
![1](https://user-images.githubusercontent.com/24897735/97183215-cce81c00-179d-11eb-90e3-da011b56aa40.png)
2.
![2](https://user-images.githubusercontent.com/24897735/97183228-d07ba300-179d-11eb-8ea4-99602bf700c3.png)
3.
![3](https://user-images.githubusercontent.com/24897735/97183234-d1acd000-179d-11eb-9419-03420304e429.png)

Stack:
```
...
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.ProcessFile(CSScriptLibrary.ScriptInfo fileInfo) Line 881
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.ProcessFile(CSScriptLibrary.ScriptInfo fileInfo) Line 881
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.ProcessFile(CSScriptLibrary.ScriptInfo fileInfo) Line 881
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.ProcessFile(CSScriptLibrary.ScriptInfo fileInfo) Line 881
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.ProcessFile(CSScriptLibrary.ScriptInfo fileInfo) Line 881
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.Init(string fileName, string[] searchDirs) Line 845
CSScriptLibrary.dll!CSScriptLibrary.ScriptParser.ScriptParser(string fileName, string[] searchDirs) Line 757
CSScriptLibrary.dll!csscript.CSExecutor.Compile(string scriptFileName) Line 1675
CSScriptLibrary.dll!csscript.CSExecutor.Compile(string scriptFile, string assemblyFile, bool debugBuild) Line 1190
CSScriptLibrary.dll!CSScriptLibrary.CSScript.CompileWithConfig(string scriptFile, string assemblyFile, bool debugBuild, csscript.Settings scriptSettings, string compilerOptions, out csscript.CompilingInfo compilingInfo, string[] refAssemblies) Line 1187
CSScriptLibrary.dll!CSScriptLibrary.CSScript.CompileWithConfig(string scriptFile, string assemblyFile, bool debugBuild, csscript.Settings scriptSettings, string compilerOptions, string[] refAssemblies) Line 1119
```

I hope you can provide a fix to this very soon. Otherwise I will have to revert to 3.28.3 or the last version before the issue was introduced.

In the meantime I will add another test case to my hosting app, in order to detect such issue with my automated test cases.

**Comment by oleg-shilo** [comment]
I will try to have a look on weekend.
Thank you for providing the test case. It is vital for investigations like that.
Publishing the fix is quick. Implementing it is a different story but it looks like something reasonably straight forward

**Comment by oleg-shilo** [comment]
After analyzing your sample I have discovered that indeed your importing technique is triggering the famous "circular dependencies" problem.

This is your `Auxiliaries.Partial.cs` file is importing itself with the `//css_imp` directive:

```C#
//css_import .\Auxiliaries.Partial.cs;

namespace TestLibrary
{
	public partial class Auxiliaries
	{
		public virtual void DoSomething()
		{
		}
	}
}

```

**Comment by maettu-this** [comment]
Back from a long weekend... Sorry for not being precise enough last week, didn't feel too well. I am aware of the circular, should have mentioned this in the issue title, will fix that in a minute.

The circular you found was caused when condensing the example to reproduce the issue, which actually is independent on the circular you found. Below comes the fix, failing with 3.30.3:
[Issue #211 @ 3.30.0 fails.zip](https://github.com/oleg-shilo/cs-script/files/5477988/Issue.211.%40.3.30.0.fails.zip)

With 3.28.3, the very same scripts perfectly works:
[Issue #211 @ 3.28.0 succeeds.zip](https://github.com/oleg-shilo/cs-script/files/5477989/Issue.211.%40.3.28.0.succeeds.zip)

So the circular is not within the same file, rather among the two parts of the partial class. I assume the functioning of 3.28.3 was coincidence, kind of a "hidden feature" you were not aware of and didn't test for. Somewhere inbetween 3.28.3 and now this "feature" got broken. Not too nice if someone used that "feature" and suddenly it's gone.

Looking at it further made me realize that I can work around the issue by not importing anything in the `.Partial.cs`. However, this didn't feel natural too me, as the now refined `.Partial.cs` actually calls a method in the central `.cs`. Therefore I implemented our partial classes including an import to the central file. Now I have realized that this is not necessary, same as e.g. with Visual Studio generated `.Designer.cs` partial class files, where the designer generated file do not need to contain any `css_import` either.

Still, it is not correct that CS-Script eventually results in a `PathTooLongException`, CS-Script should detect the issue and give a more comprehensive error message.

And maybe there should be a help on how to correctly implement partial classes, i.e. import all partials in the central file, but not import anything in the partials.

**Comment by maettu-this** [comment]
I have generalized the issue by no longer using a partial class implementation rather **A imports B imports C imports A again**.

Of course such design should be avoided, but it is fine C# code. And it works with 3.28.3:
[Generalization of Issue #211 @ 3.28.0 succeeds.zip](https://github.com/oleg-shilo/cs-script/files/5478368/Generalization.of.Issue.211.%40.3.28.0.succeeds.zip)

And fails with 3.30.3:
[Generalization of Issue #211 @ 3.30.0 fails.zip](https://github.com/oleg-shilo/cs-script/files/5478369/Generalization.of.Issue.211.%40.3.30.0.fails.zip)

While partial classes can be worked around by (unnaturally) not importing the partial central file in the partial satellite, the circular dependency among two or more classes cannot. I think CS-Script must support such valid C# code.

**Comment by maettu-this** [comment]
From my outside point of view, an implementation which continuously resolves the path of imported files and breaks recursion when detecting the same resolved file again should technically be possible.

**Comment by maettu-this** [comment]
And remember the minor one at help.txt line 274:
`cscs -config:set: ResolveRelativeFromParentScriptLocation = true`
...which should be...
`cscs -config:set:ResolveRelativeFromParentScriptLocation=true`

**Comment by oleg-shilo** [comment]
>  help.txt line 274

done

> A imports B imports C imports A again.

Will have a look. Txs

**Comment by maettu-this** [comment]
I have simplified the partial satallite class implementation, i.e. removed the circular dependency there. But still failing to compile, as our design *does use a cicular dependency similar to the generalized A imports B imports C imports A again*. It's not about the implementation of the test classes, but about the definition of test class *interfaces*. Stuck indeed... Hoping for a fix soon...

**Comment by oleg-shilo** [comment]
Will have a look tomorrow

**Comment by oleg-shilo** [comment]
Solved. A very interesting problem.

A simple concatenation of the parent script dir with the import statement  containing `.` produces perfectly valid path:
`c:\example\.\ClassAImpB.cs;` 
However the next iteration of de-referencing from the nested/imported script produces another valid path string that points to the same file:  
 `c:\example\.\.\ClassAImpB.cs;`
And then again....

And the problem is that the cs-script circular referencing protection cannot catch this case because the paths are textually not the same even though they are pointing to the same file. 

The fix is simple - normalize the imported paths with `GetFullPath`.

**_before_**
```C#
if (statement.Length > 1 && (statement[0] == '.' && statement[1] != '.')) //just a single-dot start dir
    statement = parentScript.GetDirName().PathJoin(statement);
```

**_after_**
```C#
if (statement.Length > 1 && (statement[0] == '.' && statement[1] != '.')) //just a single-dot start dir
    statement = parentScript.GetDirName().PathJoin(statement).GetFullPath();
```

Will try to squeeze the 'NewLine' issue #213 and can make a release then.
