### ISSUE TITLE
.NET 9 SDK not recognized

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#392]
Yesterday, Microsoft released .NET 9.

I've upgraded Visual Studio which now ships with .NET SDK 9 as the default.

When running the dotnet tool version of cs-script, I get the warning/error:

```
Mapping packages to assemblies...
WARNING: Cannot find .NET 8 SDK required for `dotnet` compiler engine. Switching compiler to `roslyn` instead.
To remove this warning either install .NET 8 SDK or set the default compiler engine to `roslyn` with
  css -config:set:DefaultCompilerEngine=roslyn.
```

After that, all of my existing scripts fail to compile and run with errors.

I guess this is something that comes up every year (I do not recall how it was one year ago).

Is this something I could fix on my side? Or does this require an update of cs-script?

Would it be possible for cs-script to always use the existing .NET SDK and not use a "hard-coded" version?

------------

### Update 1

Some more output:

```
C:\>css
C# Script execution engine (.NET Core). Version 4.8.19.0.
Copyright (C) 2004-2023 Oleg Shilo. www.csscript.net (github.com/oleg-shilo/cs-script)

   CLR:             8.0.11
   System:          Microsoft Windows NT 10.0.20348.0
   Architecture:    x64
   Install dir:     <not integrated>
   Script engine:   C:\Users\devops_admin\.dotnet\tools\.store\cs-script.cli\4.8.19\cs-script.cli\4.8.19\tools\net8.0\any\cscs.dll
   Launcher:        C:\Users\devops_admin\.dotnet\tools\css.exe
   Compiler engine: dotnet (C:\Program Files\dotnet\dotnet.exe)
                    WARNING: .NET 8 SDK cannot be found. It's required for `csc` and `dotnet` compiler engines.
   NuGet manager:   dotnet
   NuGet cache:     C:\Users\devops_admin\.nuget\packages
   Script cache:    C:\Users\devops_admin\AppData\Local\Temp\csscript.core\cache
   Custom commands: C:\ProgramData\cs-script\commands
   Global includes: C:\ProgramData\cs-script\inc
```

And:

```
C:\>dotnet --list-sdks
9.0.100 [C:\Program Files\dotnet\sdk]

C:\>
```

I've simply updated Visual Studio to the latest version, I have _not_ explicitly installed/uninstalled any .NET SDK separately.

-----------

### Update 2

Happend last year, too: #350

**Comment by oleg-shilo** [comment]
Thank you Uwe. 
Yes, .NET 9 is finally out and I am planning to release the build targeting the new runtime on the weekend (or so).

Though the current version of cs-script can be retargeted on the new runtime. It's a simple matter of changing the version of the target runtime in the `C:\ProgramData\chocolatey\lib\cs-script\tools\cscs.runtimeconfig.json` file.

CS-Script can even do it without manual intervention. You just need to execute `css -set-rt-self`

![image](https://github.com/user-attachments/assets/36a2ce4a-b8d3-4ca0-9fa5-ecb88bd8c609)

The following is the process of retargeting cs-script .NET 8.0 build to the freshly installed .NET 9.0 SDK 

```txt
PS C:\Users\user> gsudo css -set-rt-self
Environment Version: 8.0.10
Generating the configuration file...
C:\ProgramData\chocolatey\lib\cs-script\tools\cscs.runtimeconfig.json
C:\ProgramData\chocolatey\lib\cs-script\tools\csws.runtimeconfig.json
------------------
{
  "runtimeOptions": {
    "tfm": "net9.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "9.0.0"
      }
    ],
    "configProperties": {
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false,
      "CSWINRT_USE_WINDOWS_UI_XAML_PROJECTIONS": false
    }
  }
}
00:00:05.0046316
PS C:\Users\user> css
C# Script execution engine (.NET Core). Version 4.8.18.0.
Copyright (C) 2004-2023 Oleg Shilo. www.csscript.net (github.com/oleg-shilo/cs-script)

   CLR:             9.0.0
   System:          Microsoft Windows NT 10.0.26100.0
   Architecture:    x64
   Install dir:     C:\ProgramData\chocolatey\lib\cs-script\tools
   Script engine:   C:\ProgramData\chocolatey\lib\cs-script\tools\cscs.dll
   Launcher:        C:\ProgramData\chocolatey\lib\cs-script\tools\cscs.exe
   Compiler engine: dotnet (C:\Program Files\dotnet\dotnet.exe)
   NuGet manager:   dotnet
   NuGet cache:     C:\Users\Oleg.Shilo\.nuget\packages
   Script cache:    C:\Users\Oleg.Shilo\AppData\Local\Temp\csscript.core\cache
   Custom commands: C:\ProgramData\cs-script\commands
   Global includes: C:\ProgramData\cs-script\inc
```
This should help until the new build is available.

**Comment by UweKeim** [comment]
Thanks, @oleg-shilo 

The "self thing" doesn't seem to work:

```
C:\>css -set-rt-self
Could not find file "-set-rt-self".
Ensure it is in one of the CS-Script search/probing directories.
```

I'll try to do it the manual way as you described.

**Comment by oleg-shilo** [comment]
Great. You are good for now and I will release the new build soon.

> The "self thing" doesn't seem to work:

It means that you do not have the extended cs-script commands installed. I will check why .NET Tool does not distribute them.

With choco it does. You can always check it with `css -cmd`:

![image](https://github.com/user-attachments/assets/d3c86fb5-ff14-4524-9894-9ce4db95f2fd)

And the commands (scripts) are located here: `C:\ProgramData\chocolatey\lib\cs-script\tools\-set\-rt`
![image](https://github.com/user-attachments/assets/9b6562cc-5d0d-4457-a56b-5a66ffb4c61c)

**Comment by UweKeim** [comment]
Would be awesome if the .NET Tool version of CS-Script could include this `-set-rt-self`, too:

Since I'm using the .NET Tool version of CS-Script in my GitLab CI/CD scripts (Linux), and thus cannot manually edit the "cscs.runtimeconfig.json", I would love to have my script be able to re-target itself to the .NET SDK version Docker image it is currently running.

**Comment by oleg-shilo** [comment]
Yep. Agree. It makes sense to align the NET NET-tool with the choco model.
Working on it....

**Comment by UweKeim** [comment]
Personally, I doubt that calling CS-Script with `-set-rt-self` when _not_ having the currently configured .NET SDK on my machine could even work, since it wouldn't start the application at the first place because of the missing SDK?

Hopefully I'm wrong with my assumption 😊.

**Comment by oleg-shilo** [comment]
The solution to the problem is not symmetrical. There are two scenarios that I will illustrate with .net8 vs .net9 use case:
1. You have an application (e.g. cscs.dll) that is targets .NET8 and you have .NET8 configured as your active .NET SDK
   -  you have installed a new SDN .NET9, which becomes your active .NET SDK. This lead to the situation when you can run cscs.dll (since you still have your .NET8 runtime) but you cannot run scripts as they are compiled as .NET9 assemblies and cannot load to your .NET8 script engine .NET8 hosting runtime. 
   - `-set-rt-self` solves the problem very easily.
1. You have an application (e.g. cscs.dll) that targets .NET8 and you have only .NET9 configured as your active .NET SDK
   -  You cannot run any .NET8 targeting application, including cscs.dll .NET SDK. This lead to the situation when you cannot run the scrip engine at all unless you modify cscs.runtimeconfig.json manually.
   - `-set-rt-self` is useless as it cannot be executed until you install .NET8

Thus you are right. The benefits are not undisputable. But it still makes sense to bring all these custom commands to the distro: 
- `-mkshim` choco style shim builder (no need to install Chocolatey). Win only.
- `-self`: Prints path to the script engine CLI executable.
- `self-alias`: Builds `css.exe` hard-link to the script engine CLI executable.
- `self-exe`: Builds `css.exe` that executes the script engine CLI executable. It is an alternative to the symbolic links or true shims.
- `-set-rt`: Sets the specified assembly(s) target runtime to the currently active .NET configuration.
- `-set-rt-self`: Sets the cs-script engine target runtime to the currently active .NET configuration.
- `-wdbg`: Start web-based debugger (wdbg) for the specified script.
- `-web`: CS-Script custom command for starting a Web server to service static files.

![image](https://github.com/user-attachments/assets/ed3fb718-dd43-4763-8d33-aa562a215f3a)

---

However, now I am thinking that a native executable that allows patching `*.runtimeconfig.json` without any dependency on .NET can be a better solution. But it is an idea for future releases.

**Comment by UweKeim** [comment]
My CICD job still hangs forever at CS-Script, after modifying the runtimeconfig JSON file.

I've enabled `-verbose` and this is the output:

```
$ ~/.dotnet/tools/css -config:set:LegacyNugetSupport=false
set: LegacyNugetSupport: False
$ ~/.dotnet/tools/css -verbose -dbg ${CI_PROJECT_DIR}/Source/cicd-increase-versionnumber.cs
Restoring packages...
Mapping packages to assemblies...
> ----------------
  Provider: 
  Script engine: /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
  Compiler engine: csc (/usr/share/dotnet/sdk/9.0.100/Roslyn/bincore/csc.dll)
                   of dotnet (/usr/share/dotnet/dotnet)
  Console Encoding: utf-8 (Unicode (UTF-8)) - system default
  CurrentDirectory: /builds/ukeim/formfeld/Source
  CurrentProcess: 231
  NuGet manager: dotnet
  NuGet cache: /root/.nuget/packages
  Script cache: /tmp/csscript.core/cache
  Executing: /builds/ukeim/formfeld/Source/cicd-increase-versionnumber.cs
  Hosting: InProcess
  Script arguments: 
  SearchDirectories: 
    ------- (local dirs) -------
    0 - /builds/ukeim/formfeld/Source
    1 - /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any
    ------- (dirs from cmd args) -------
    ------- (dirs from code) -------
    2 - /root/.nuget/packages/sharpziplib/1.4.2/lib/net6.0
    3 - /root/.nuget/packages/jetbrains.annotations/2023.3.0/lib/netstandard2.0
    4 - /root/.nuget/packages/morelinq/4.3.0/lib/net8.0
    5 - /root/.nuget/packages/newtonsoft.json/13.0.3/lib/net6.0
    6 - /root/.nuget/packages/nuget.versioning/6.12.1/lib/netstandard2.0
    7 - /root/.nuget/packages/restsharp/112.1.0/lib/net8.0
    8 - /root/.nuget/packages/zetadeployer.runtimeuploader/1.0.96/lib/net8.0
    9 - /root/.nuget/packages/zetashortpaths/2.0.41/lib/net8.0
    ------- (dirs from config) -------
    10 - /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/lib
    11 - /usr/share/cs-script/commands
    12 - /builds/ukeim/formfeld/Source/%CSSCRIPT_INC%
    ------- (cs-script special dirs) -------
    13 - /tmp/csscript.core/cache/-2[87](https://git.zeta-sw.com/ukeim/formfeld/-/jobs/11973#L87)780190
> ----------------
Compiling script...
  Precompilers: 
   0 - cicd-increase-versionnumber.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   1 - Afx.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   2 - AppOfflineUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   3 - BuildUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   4 - CompilationUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   5 - FileSyncUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   6 - FileUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   7 - FolderUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   8 - FolderXCopy.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   9 - FolderXCopyUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   10 - FolderZip.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   11 - Logging.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   12 - ProcessUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   13 - SpecialFolders.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
   14 - StringUtilities.cs -> csscript.DefaultPrecompiler
           from /root/.dotnet/tools/.store/cs-script.cli/4.8.19/cs-script.cli/4.8.19/tools/net8.0/any/cscs.dll
Restoring packages...
Mapping packages to assemblies...
  Output file: 
       /tmp/csscript.core/cache/-2877801[90](https://git.zeta-sw.com/ukeim/formfeld/-/jobs/11973#L90)/cicd-increase-versionnumber.cs.dll
  Files to compile: 
   0 - /builds/ukeim/formfeld/Source/cicd-increase-versionnumber.cs
   1 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/Afx.cs
   2 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/AppOfflineUtilities.cs
   3 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/BuildUtilities.cs
   4 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/CompilationUtilities.cs
   5 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/FileSyncUtilities.cs
   6 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/FileUtilities.cs
   7 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/FolderUtilities.cs
   8 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/FolderXCopy.cs
   9 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/FolderXCopyUtilities.cs
   10 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/FolderZip.cs
   11 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/Logging.cs
   12 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/ProcessUtilities.cs
   13 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/SpecialFolders.cs
   14 - /builds/ukeim/formfeld/_References/Submodules/zeta-shared-ci-assets/DevelopmentTools/CentralScripts/StringUtilities.cs
   15 - /tmp/csscript.core/cache/-287780190/cicd-increase-versionnumber.attr.g.cs
  References: 
   0 - System
   1 - /root/.nuget/packages/morelinq/4.3.0/lib/net8.0/MoreLinq.dll
   2 - System.Core
   3 - /root/.nuget/packages/nuget.versioning/6.12.1/lib/netstandard2.0/NuGet.Versioning.dll
   4 - /root/.nuget/packages/restsharp/112.1.0/lib/net8.0/RestSharp.dll
   5 - /root/.nuget/packages/sharpziplib/1.4.2/lib/net6.0/ICSharpCode.SharpZipLib.dll
   6 - /root/.nuget/packages/zetadeployer.runtimeuploader/1.0.[96](https://git.zeta-sw.com/ukeim/formfeld/-/jobs/11973#L96)/lib/net8.0/ZetaDeployer.RuntimeUploader.dll
   7 - /root/.nuget/packages/newtonsoft.json/13.0.3/lib/net6.0/Newtonsoft.Json.dll
   8 - /root/.nuget/packages/zetashortpaths/2.0.41/lib/net8.0/ZetaShortPaths.dll
   9 - /root/.nuget/packages/jetbrains.annotations/2023.3.0/lib/netstandard2.0/JetBrains.Annotations.dll
> ----------------
```

Is there any reason you could think of that could cause this endless hang?

**Comment by UweKeim** [comment]
> However, now I am thinking that a native executable that allows patching `*.runtimeconfig.json` without any dependency on .NET can be a better solution. But it is an idea for future releases.

You could do this even with .NET itself and statically link with the .NET runtime into a single executable.

Personally, I love this idea, even if this would result in an executable about 30-60 MB of size.

**Comment by oleg-shilo** [comment]
Yah, I an working on this now.

Self-contained exe is not a good option for that. The file becomes huge (it now contains the whole .NET runtime. And it needs to be built into native executables for all possible target OSs. So I have abandoned this idea.

I am not building two .NET-Tool packages `cs-script.cli` and `cs-script.cli.net8`.
This way you will be able to install the tool version that you need. `cs-script.cli` will be able to retarget itself to future runtimes with `-set-rt-self` until I release the new `cs-script.cli` package. And `cs-script.cli` and `cs-script.cli.net8` will be always identical (functionality-wise). 

The ability to use the assembly specifically built for your runtime is a more accurate technique than changing `.runtimeconfig.json`, even though it will still be available.

I will release it as soon as I finish updating the packaging algorithm. Doing it right now.

**Comment by UweKeim** [comment]
This sounds promising, thank you 😊.

So in the future, there will be `cs-script.cli.net8`, `cs-script.cli.net9`, `cs-script.cli.net10`, ... and always a `cs-script.cli` which is similar to the currently latest .NET version?

With this idea, I do think you could also publish `cs-script.cli.net9` together with `cs-script.cli` right now so that it would be easier within my CI-CD jobs to address the correct runtime.

Microsoft does it similar with [their Docker images of .NET SDK](https://hub.docker.com/r/microsoft/dotnet-sdk) which I'm using in my CI-CD jobs.

**Comment by oleg-shilo** [comment]
Yep the idea is:

- `cs-script.cli` - the latest version of cs-script targeting the latest version of .NET
- `cs-script.cli.net8` - the latest version of cs-script targeting .NET8. The package updates stop after .NET10 is released
- `cs-script.cli.net9` - the latest version of cs-script targeting .NET9. The package updates stop after .NET11 is released
- . . .

**Comment by oleg-shilo** [comment]
It might be even more stright forward...
I managed to built a multitarget package (by default .NET project always targets only one runtime). meaning that it's a single package that includes both dstros but installs only one that is install one that has the corresponding .NET installed on the target system.

Will need to properly test it and will release after that.

![image](https://github.com/user-attachments/assets/6c6872ff-7d35-4638-ba02-d408c8897806)

**Comment by UweKeim** [comment]
Under Windows, after upgrading to 4.8.21.0, there is also no more "css", only a "css2".

**Comment by oleg-shilo** [comment]
OH my. that's my mistake. 
I did a temp change in the nuget package to allow an alternative command so choco and dotnet installs do not clash during the testing. Wanted to ensure no mistakes were made. 

Fixed now. The package 4.8.21.1

What is great about .NET Tool channel is that the publishing process is so streamlined that it takes me less than a minute to republish it.

**Comment by UweKeim** [comment]
Thank you very much for you fix, Oleg!

And sorry for all the trouble and work you had because of this issue of mine.

**Comment by UweKeim** [comment]
Just for completeness, I'm still getting randomly getting timeout errors in _some_ of my CI-CD scripts, even without modifying the runtimeconfig JSON file and the newest CS-Script version:

```
$ dotnet tool install --global cs-script.cli
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:
cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF
You can add it to the current session by running the following command:
export PATH="$PATH:/root/.dotnet/tools"
You can invoke the tool using the following command: css
Tool 'cs-script.cli' (version '4.8.[21](https://git.zeta-sw.com/zeta/zeta-shared-ci-assets/-/jobs/12080#L21).1') was successfully installed.
$ dotnet tool update --global cs-script.cli
Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:
cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF
You can add it to the current session by running the following command:
export PATH="$PATH:/root/.dotnet/tools"
Tool 'cs-script.cli' was reinstalled with the stable version (version '4.8.21.1').
$ ~/.dotnet/tools/css -config:set:LegacyNugetSupport=false
set: LegacyNugetSupport: False
$ ~/.dotnet/tools/css ${CI_PROJECT_DIR}/Etc/Testing/cicd-test-04.cs
Restoring packages...
Mapping packages to assemblies...
Restoring packages...
Mapping packages to assemblies...
WARNING: step_script could not run to completion because the timeout was exceeded. For more control over job and script timeouts see: https://docs.gitlab.com/ee/ci/runners/configure_runners.html#set-script-and-after_script-timeouts
ERROR: Job failed: execution took longer than 1h0m0s seconds
```

So _maybe_ there is something in the way that CS-Script doing with restoring/mapping NuGet packages that .NET 9 doesn't like?

At least sometimes?

**Comment by oleg-shilo** [comment]
Hi Uwe,

I am not sure what's going on there. 
Just to give you the context on processing nuget packages with cs-script. 
- downloading the packages: it is dome purely by .NET. CS-Script just creates the .NET project with all the packages there and publishes it. This ensures that all the assemblies are downloaded and aggregated by the dotnet.exe
- resolving the packages to the assemblies to be referenced: this is what cs-script does
    - `LegacyNugetSupport == true`
       CS-Script opens every *.nuspec file in the appropriate package version folder and notes a DLL to be referenced. It also analyses its XML content and notes any dependency package. 
    - `LegacyNugetSupport == false`
       CS-Script opens the folder where the project was published and takes note of all DLLs aggregated there.
       
   Then it returns the result as a `//css_ref <path>` multiline list to be saved in the temp folder as a script containing only //css_ref instructions and includes this script in your primary script.
   
It's not much that can go wrong.
Though. I debugged your scenario and noticed that the aggregation of the dll's (analysis) is done accidentally twice. It's not a problem as the result is the same but it's not efficient and effectively the analysis (not downloading) time is doubled.

This if you have so many files to analyse that it takes more than 30 mins to do then indeed it can trigger the 1 hour timeout.

I do not see anything else there :(

**Comment by UweKeim** [comment]
Thank you, Oleg!

The only thing I could think of would be an endless recursion with noch break condition being hit. But in my opinion this would mean that it happens in all of my scripts, since they are basically all very similar, not just some (randomly?) selected ones that include the same things as all the other scripts that run perfectly.

Hopefully I find an explanation some day, I'll keep investigating.

**Comment by oleg-shilo** [comment]
agree. recursion is a suspect.
Though, `LegacyNugetSupport == false` would disable cyclic discovery. I know yu yu prefer the legacy algorithm but you can try it. BTW `LegacyNugetSupport == true` is the default setting
